[Docs] DDD
Sylius/Stack pull request #196
Opened 2024-12-23 11:05 UTC by loic425

2024-12-23 20:18 UTC, diimpp commented on docs/cookbook/ddd_architecture/basic_operations.md
> +final class BookResource implements ResourceInterface
Missing `ResourceInterface` at `use` block.

2024-12-23 20:18 UTC, diimpp commented on docs/cookbook/ddd_architecture/basic_operations.md
> +            // formType: CreateBookResourceType::class, // Optional: define a specific form type only for the "update" operation
```suggestion
            // formType: UpdateBookResourceType::class, // Optional: define a specific form type only for the "update" operation
```

2024-12-23 20:18 UTC, diimpp commented on docs/cookbook/ddd_architecture/basic_operations.md
> +We need to write the `DeleteBookProcessor`.
```suggestion
We need to create the `DeleteBookProcessor`.
```

2024-12-23 20:18 UTC, diimpp commented on docs/cookbook/ddd_architecture/grid.md
> +First we need to write the `BookGridProvider`.
```suggestion
First we need to create the `BookGridProvider`.
```

2024-12-23 20:18 UTC, diimpp commented on docs/cookbook/ddd_architecture/grid.md
> +    formType: BookResourceType::class, // Define the form type for all your operations
Both `BookResourceType` and `ResourceInterface` probably should be added to `use` block

2024-12-23 20:18 UTC, diimpp commented on docs/cookbook/ddd_architecture/grid.md
> +
```suggestion
```

2024-12-23 20:18 UTC, diimpp commented on docs/cookbook/ddd_architecture/overview.md
> +The whole codebase of the DDD application example is available on [Github](https://github.com/loic425/sylius-stack-ddd).
Should this example app be moved to sylius namespace eventually?

2025-01-02 07:57 UTC, loic425 commented on docs/cookbook/ddd_architecture/grid.md
> +    formType: BookResourceType::class, // Define the form type for all your operations
done

2025-01-02 07:57 UTC, loic425 commented on docs/cookbook/ddd_architecture/grid.md
> +
done

2025-01-02 07:58 UTC, loic425 commented on docs/cookbook/ddd_architecture/overview.md
> +The whole codebase of the DDD application example is available on [Github](https://github.com/loic425/sylius-stack-ddd).
Yes, indeed, but we need to ask for the Sylius team.

2025-01-02 11:27 UTC, loic425 commented on docs/cookbook/ddd_architecture/basic_operations.md
> +final class BookResource implements ResourceInterface
done

2025-01-02 15:47 UTC, stlgaits requested changes

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture.md
> +Here we present a lot of tips to help you to integrate the Sylius stack components in your clean architecture.
```suggestion
Here, we present a lot of tips to help you integrate the Sylius Stack components in your clean architecture.
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture.md
> +In this cookbook we reuse the apip-ddd project from Mathias Arlaud and Robin Chalas for their excellent __Domain-driven design with API Platform 3__ talk.
```suggestion
In this cookbook, we reuse Mathias Arlaud's and Robin Chalas's [apip-ddd project](https://github.com/mtarld/apip-ddd) presented during their excellent __Domain-driven design with API Platform 3__ talk.
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/basic_operations.md
> +In previous chapter, we have created the Sylius resource. Now we need to create the basic operations.
```suggestion
In the previous chapter, we have created the Sylius resource. Now we need to create the basic operations.
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/basic_operations.md
> +The idea is to reuse this command to create the book in the storage for your "create" operation.
I'm not sure how but I think this sentence should be rephrased to be less repetitive

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/basic_operations.md
> +First we need to write the `CreateBookProcessor`.
```suggestion
First, we need to add the `CreateBookProcessor` in which we're going to call our `CreateBookCommand`.
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/basic_operations.md
> +And then we create the "update" operation on our BookResource.
```suggestion
Then, we add the `Create` operation on our `BookResource`.
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/basic_operations.md
> +In the Application folder, we already have this `UpdateBookCommand`:
```suggestion
Now, we want to be able to edit an existing book. In the Application folder, we already have this `UpdateBookCommand`:
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/basic_operations.md
> +The idea is to reuse these query and command to update the book in the storage for your "update" operation.
Same comment as above, I'm not sure how but I think this sentence should be rephrased to be less repetitive

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/basic_operations.md
> +First, we need to create the `BookItemProvider`.
```suggestion
First, we need to create the `BookItemProvider` in order to fetch the right book.
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/basic_operations.md
> +We also need to create the `UpdateBookProcessor`.
```suggestion
We also need to create the `UpdateBookProcessor` where we're going to call our `UpdateBookCommand`.
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/basic_operations.md
> +And then we create the "update" operation on the BookResource.
```suggestion
Now, we add the "update" operation on the `BookResource`.
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/basic_operations.md
> +In the Application folder, we already have this `DeleteBookCommand`:
```suggestion
Now that we can update an existing book, we also want to be able to delete it. In the Application folder, we already have this `DeleteBookCommand`:
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/grid.md
> +First we need to create the `BookGridProvider`.
```suggestion
First, we need to create the `BookGridProvider`.
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/grid.md
> +We also need to create the `BookGrid`.
```suggestion
Now, we need to create the `BookGrid`.
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/grid.md
> +And then we create the "update" operation on our BookResource.
```suggestion
Now that we have a grid, let's add it to the "index" operation on our `BookResource`.
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/grid.md
> +First, we need to create a Symfony form type for our custom author filter.
```suggestion
Let's imagine we want to be able to filter books by their author within our grid. First, we need to create a Symfony form type for our custom author filter.
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/grid.md
> +        // Authors are stored on the Book resource
```suggestion
        // Authors are stored in the Book resource
```

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/grid.md
> +        throw new \RuntimeException('Not implemented'); // We cannot use the DataSource generic abstraction
maybe worth explaining why not?

2025-01-02 15:47 UTC, stlgaits commented on docs/cookbook/ddd_architecture/grid.md
> +        $criteria = $parameters->get('criteria', []); // Getting the criteria on query params
```suggestion
        $criteria = $parameters->get('criteria', []); // Getting the criteria from query params
```

2025-01-03 08:43 UTC, loic425 commented on docs/cookbook/ddd_architecture/grid.md
> +        throw new \RuntimeException('Not implemented'); // We cannot use the DataSource generic abstraction
Hum indeed, that could be interesting to add this on the cookbook.

2025-01-03 08:46 UTC, loic425 commented on docs/cookbook/ddd_architecture/overview.md
> +The whole codebase of the DDD application example is available on [Github](https://github.com/loic425/sylius-stack-ddd).
Let's start with this one, we are able to move this repo later.

2025-01-03 08:49 UTC, stlgaits approved these changes

2025-01-06 11:12 UTC, diimpp approved these changes

2025-01-06 13:24 UTC, merged